A small hack to get the circleci artifacts for an old commit

diff --git a/initrd/bin/gui-init b/initrd/bin/gui-init
--- a/initrd/bin/gui-init
+++ b/initrd/bin/gui-init
@@ -42,12 +42,12 @@ verify_global_hashes()
   TMP_PACKAGE_TRIGGER_PRE="/tmp/kexec/kexec_package_trigger_pre.txt"
   TMP_PACKAGE_TRIGGER_POST="/tmp/kexec/kexec_package_trigger_post.txt"
 
-  if ( cd /boot && sha256sum -c "$TMP_HASH_FILE" > /tmp/hash_output ) then
+  if cd /boot && sha256sum -c "$TMP_HASH_FILE" > /tmp/hash_output ; then
     return 0
   elif [ ! -f $TMP_HASH_FILE ]; then
     if (whiptail $CONFIG_ERROR_BG_COLOR --clear --title 'ERROR: Missing Hash File!' \
       --yesno "The file containing hashes for /boot is missing!\n\nIf you are setting this system up for the first time, select Yes to update\nyour list of checksums.\n\nOtherwise this could indicate a compromise and you should select No to\nreturn to the main menu.\n\nWould you like to update your checksums now?" 30 90) then
-      update_checksums
+      prompt_update_checksums
     fi
     return 1
   else
@@ -70,11 +70,11 @@ verify_global_hashes()
       fi
 
     else
-      TEXT="The following files failed the verification process:\n\n${CHANGED_FILES}\n\nThis could indicate a compromise!\n\nWould you like to update your checksums now?"
+      TEXT="The following files failed the verification process:\n${CHANGED_FILES}\n\nThis could indicate a compromise!\n\nWould you like to update your checksums now?"
     fi
 
     if (whiptail $CONFIG_ERROR_BG_COLOR --clear --title 'ERROR: Boot Hash Mismatch' --yesno "$TEXT" 30 90) then
-      update_checksums
+      prompt_update_checksums
     fi
     return 1
   fi
@@ -82,7 +82,7 @@ verify_global_hashes()
 prompt_update_checksums()
 {
   if (whiptail --title 'Update Checksums and sign all files in /boot' \
-      --yesno "You have chosen to update the checksums and sign all of the files in /boot.\n\nThis means that you trust that these files have not been tampered with.\n\nYou will need your GPG key available, and this change will modify your disk.\n\nDo you want to continue?" 16 90) then
+      --yesno "You have chosen to update the checksums and sign all of the files in /boot.\n\nThis means that you trust that the files in /boot have not been tampered with.\n\nYou will need your GPG key to continue and this change will modify your disk.\n\nDo you want to continue?" 16 90) then
     update_checksums
   else
     echo "Returning to the main menu"
@@ -92,10 +92,10 @@ update_totp()
 {
   echo "Scan the QR code to add the new TOTP secret"
   /bin/seal-totp
-  if [ -x /bin/hotp_verification ]; then
-    echo "Once you have scanned the QR code, hit Enter to configure your HOTP USB Security Dongle (e.g. Librem Key or Nitrokey)"
+  if [ -x /bin/libremkey_hotp_verification ]; then
+    echo "Once you have scanned the QR code, hit Enter to configure your Librem Key"
     read
-    /bin/seal-hotpkey
+    /bin/seal-libremkey
   else
     echo "Once you have scanned the QR code, hit Enter to continue"
     read
@@ -118,11 +118,8 @@ clean_boot_check()
   [ $GPG_KEY_COUNT -ne 0 ] && return
 
    # check for USB security token
-  if [ "$CONFIG_HOTPKEY" = "y" ]; then
-    enable_usb
-    if ! gpg --card-status > /dev/null ; then
-      return
-    fi
+  if ! gpg --card-status > /dev/null ; then
+   return
   fi
 
   # OS is installed, no kexec files present, no GPG keys in keyring, security token present
@@ -131,6 +128,9 @@ clean_boot_check()
     "Clean Boot Detected - Perform OEM Factory Reset?" "$CONFIG_WARNING_BG_COLOR"
 }
 
+# enable USB to load modules for external kb
+enable_usb
+
 if detect_boot_device ; then
   # /boot device with installed OS found
   clean_boot_check
@@ -138,13 +138,6 @@ else
   # can't determine /boot device or no OS installed, 
   # so fall back to interactive selection
   mount_boot
-fi
-
-# Use stored HOTP key branding
-if [ -r /boot/kexec_hotp_key ]; then
-	HOTPKEY_BRANDING="$(cat /boot/kexec_hotp_key)"
-else
-	HOTPKEY_BRANDING="HOTP USB Security Dongle"
 fi
 
 last_half=X
@@ -195,16 +188,14 @@ while true; do
   fi
 
   if [ "$totp_confirm" = "i" -o -z "$totp_confirm" ]; then 
-    if [ -x /bin/hotp_verification ]; then
+    if [ -x /bin/libremkey_hotp_verification ]; then
       HOTP=`unseal-hotp`
       enable_usb
-      if ! hotp_verification info ; then
-        whiptail $CONFIG_WARNING_BG_COLOR --clear \
-	--title "WARNING: Please Insert Your $HOTPKEY_BRANDING" \
-	--msgbox "Your $HOTPKEY_BRANDING was not detected.\n\nPlease insert your $HOTPKEY_BRANDING" 30 90
+      if ! libremkey_hotp_verification info ; then
+        whiptail $CONFIG_WARNING_BG_COLOR --clear --title 'WARNING: Please Insert Your Librem Key' --msgbox "Your Librem Key was not detected.\n\nPlease insert your Librem Key" 30 90
         fi
       # Don't output HOTP codes to screen, so as to make replay attacks harder
-      hotp_verification check $HOTP
+      libremkey_hotp_verification check $HOTP
       case "$?" in
         0 )
           HOTP="Success"
@@ -214,7 +205,7 @@ while true; do
           MAIN_MENU_BG_COLOR=$CONFIG_ERROR_BG_COLOR
         ;;
         * )
-          HOTP="Error checking code, Insert $HOTPKEY_BRANDING and retry"
+          HOTP="Error checking code, Insert Librem Key and retry"
           MAIN_MENU_BG_COLOR=$CONFIG_WARNING_BG_COLOR
         ;;
       esac
@@ -227,7 +218,6 @@ while true; do
       'y' ' Default boot' \
       'r' ' Refresh TOTP/HOTP' \
       'a' ' Options -->' \
-      'S' ' System Info' \
       'P' ' Power Off' \
       2>/tmp/whiptail || recovery "GUI menu failed"
 
@@ -313,34 +303,30 @@ while true; do
   fi
 
   if [ "$totp_confirm" = "p" ]; then
-    if [ "$CONFIG_TPM" = "y" ]; then
-      if (whiptail --title 'Reset the TPM' \
-          --yesno "This will clear the TPM and TPM password, replace them with new ones!\n\nDo you want to proceed?" 16 90) then
-        /bin/tpm-reset
+    if (whiptail --title 'Reset the TPM' \
+        --yesno "This will clear the TPM and TPM password, replace them with new ones!\n\nDo you want to proceed?" 16 90) then
+      /bin/tpm-reset
 
-        # now that the TPM is reset, remove invalid TPM counter files
-        mount_boot
-        mount -o rw,remount /boot
-        rm -f /boot/kexec_rollback.txt
+      # now that the TPM is reset, remove invalid TPM counter files
+      mount_boot
+      mount -o rw,remount /boot
+      rm -f /boot/kexec_rollback.txt
 
-        # create Heads TPM counter before any others
-        check_tpm_counter /boot/kexec_rollback.txt \
-        || die "Unable to find/create tpm counter"
-        counter="$TPM_COUNTER"
+      # create Heads TPM counter before any others
+      check_tpm_counter /boot/kexec_rollback.txt \
+      || die "Unable to find/create tpm counter"
+      counter="$TPM_COUNTER"
 
-        increment_tpm_counter $counter \
-        || die "Unable to increment tpm counter"
+      increment_tpm_counter $counter \
+      || die "Unable to increment tpm counter"
 
-        sha256sum /tmp/counter-$counter > /boot/kexec_rollback.txt \
-        || die "Unable to create rollback file"
-        mount -o ro,remount /boot
+      sha256sum /tmp/counter-$counter > /boot/kexec_rollback.txt \
+      || die "Unable to create rollback file"
+      mount -o ro,remount /boot
 
-        update_totp
-      else
-        echo "Returning to the main menu"
-      fi
+      update_totp
     else
-      whiptail --clear --title 'ERROR: No TPM Detected' --msgbox "This device does not have a TPM.\n\nPress OK to return to the Main Menu" 30 90
+      echo "Returning to the main menu"
     fi
     continue
   fi
@@ -385,15 +371,6 @@ while true; do
 
   if [ "$totp_confirm" = "G" ]; then
     gpg-gui.sh
-    continue
-  fi
-
-  if [ "$totp_confirm" = "S" ]; then
-    memtotal=$(cat /proc/meminfo | grep 'MemTotal' | tr -s ' ' | cut -f2 -d ' ')
-    memtotal=$((${memtotal} / 1024 / 1024 + 1))
-    cpustr=$(cat /proc/cpuinfo | grep 'model name' | uniq | sed -r 's/\(R\)//;s/\(TM\)//;s/CPU //;s/model name.*: //')
-    whiptail --title 'System Info' \
-      --msgbox "VER: ${FW_VER}\n\nCPU: ${cpustr}\nRAM: ${memtotal} GB\n\n$(fdisk -l | grep -e '/dev/sd.:' -e '/dev/nvme.*:' | sed 's/B,.*/B/')" 16 60
     continue
   fi
 
diff --git a/initrd/bin/usb-scan b/initrd/bin/usb-scan
--- a/initrd/bin/usb-scan
+++ b/initrd/bin/usb-scan
@@ -2,7 +2,6 @@
 # Scan for USB installation options
 set -e -o pipefail
 . /etc/functions
-. /etc/gui_functions
 . /tmp/config
 
 # Unmount any previous boot device
@@ -12,10 +11,10 @@ if grep -q /boot /proc/mounts ; then
 fi
 
 # Mount the USB boot device
-mount_usb || die "Unable to mount /media"
-
-# Get USB boot device
-USB_BOOT_DEV=$(grep "/media" /etc/mtab | cut -f 1 -d' ')
+if ! grep -q /media /proc/mounts ; then
+	mount-usb "$CONFIG_USB_BOOT_DEV" \
+		|| die "Unable to mount /media"
+fi
 
 # Check for ISO first
 get_menu_option() {
@@ -73,7 +72,7 @@ if [ `cat /tmp/iso_menu.txt | wc -l` -gt 0 ]; then
 	if [ -n "$option" ]; then
 		MOUNTED_ISO=$option
 		ISO=${option:7} # remove /media/ to get device relative path
-		kexec-iso-init $MOUNTED_ISO $ISO $USB_BOOT_DEV
+		kexec-iso-init $MOUNTED_ISO $ISO $CONFIG_USB_BOOT_DEV
 
 		die "Something failed in iso init"
 	fi
